apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: mentorify
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: mentorify
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
