{
 "title": "Mentorify Main Dashboard",
 "tags": [ "mentorify" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "TOP 5 CPU Consumers (Entire Cluster)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{container!='', container!='POD'}[5m])) by (pod, namespace))",
     "legendFormat": "{{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "Mentorify - CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='mentorify', container!='', container!='POD'}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mentorify - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='mentorify', container!='', container!='POD'}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}