apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mentorify-ingress
  namespace: mentorify
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    # 1. Direkt IP üzerinden erişim için (Host header gerektirmeyen kural)
    - http:
        paths: &paths
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 8800
          - path: /public/uploads
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 8800
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 8800
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 3000
    # 2. sslip.io üzerinden erişim
    - host: mentorify.89.252.153.121.sslip.io
      http:
        paths: *paths
