apiVersion: v1
kind: ConfigMap
metadata:
  name: mentorify-config
  namespace: mentorify
  labels:
    app.kubernetes.io/part-of: mentorify
data:
  NODE_ENV: "production"
  PORT: "8800"
  API_URL: "/api/v1"
  FRONT_HOST: "https://mentorify.devlermedya.net"
  IYZICO_BASE_URL: "https://sandbox-api.iyzipay.com"

  # Internal service URLs (k8s DNS)
  FRONTEND_URL: "http://frontend-svc.mentorify.svc.cluster.local:3000"
  BACKEND_URL: "http://backend-svc.mentorify.svc.cluster.local:8800"

  # Frontend'in hem içeriden hem dışarıdan kullanacağı adres
  SECRET_API: "https://mentorify.devlermedya.net"
