apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.24.1
    chart: victoria-metrics-k8s-stack
    helm:
      values: |
        # VictoriaMetrics Single node (Cluster modu kapalı, az kaynak harcar)
        vmsingle:
          enabled: true
          spec:
            retentionPeriod: "14d"
            storage:
              accessModes: ["ReadWriteOnce"]
              storageClassName: local-path
              resources:
                requests:
                  storage: 10Gi
        
        # Diğer ağır bileşenleri kapatıyoruz
        vmalert:
          enabled: false
        vmagent:
          enabled: true # Metrikleri toplamak için lazım
        
        # Grafana ayarları
        grafana:
          enabled: true
          adminPassword: admin
          ingress:
            enabled: false # Makinedeki Ingress'i kullanacağız
        
        # Node exporter ve Kube-state-metrics (CPU/RAM görmemiz için lazım)
        prometheus-node-exporter:
          enabled: true
        kube-state-metrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
