apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.24.1
    chart: victoria-metrics-k8s-stack
    helm:
      values: |
        # İsimlerin 63 karakteri aşmaması için kısaltıyoruz
        fullnameOverride: vmstack
        nameOverride: vms
        
        # VictoriaMetrics Single node
        vmsingle:
          enabled: true
          spec:
            retentionPeriod: "14d"
            storage:
              accessModes: ["ReadWriteOnce"]
              storageClassName: local-path
              resources:
                requests:
                  storage: 10Gi
        
        vmalert:
          enabled: false
        vmagent:
          enabled: true
        
        grafana:
          enabled: true
          adminPassword: admin
          fullnameOverride: grafana # Grafana ismini de kısaltalım
          ingress:
            enabled: false
        
        prometheus-node-exporter:
          enabled: true
          fullnameOverride: node-exporter
        kube-state-metrics:
          enabled: true
          fullnameOverride: ksm
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
